"""
Complete Space Rename Solution
===============================
1. Identifies which databases matter for nys-voter-pipeline
2. Generates complete SQL with proper column types
3. Searches all .py files for references to tables/columns with spaces
4. Creates backup before making changes
"""
import pymysql
import os
import json
from dotenv import load_dotenv

load_dotenv()

def connect_db():
    return pymysql.connect(
        host=os.getenv('MYSQL_HOST'),
        user=os.getenv('MYSQL_USER'),
        password=os.getenv('MYSQL_PASSWORD'),
        port=int(os.getenv('MYSQL_PORT')),
        charset='utf8mb4'
    )

def get_column_definition(cursor, db, table, column):
    """Get full column definition for CHANGE statement"""
    cursor.execute(f"USE `{db}`")
    cursor.execute(f"SHOW FULL COLUMNS FROM `{table}` WHERE Field = %s", (column,))
    row = cursor.fetchone()
    
    if not row:
        return None
    
    # row format: Field, Type, Collation, Null, Key, Default, Extra, Privileges, Comment
    field_type = row[1]
    nullable = "NULL" if row[3] == "YES" else "NOT NULL"
    default = f"DEFAULT {row[5]}" if row[5] is not None else ""
    extra = row[6] if row[6] else ""
    collation = row[2]
    
    # Build full definition
    definition = f"{field_type}"
    if collation and 'utf8mb4' in str(collation):
        definition += f" CHARACTER SET utf8mb4 COLLATE {collation}"
    definition += f" {nullable}"
    if default:
        definition += f" {default}"
    if extra:
        definition += f" {extra}"
    
    return definition.strip()

def main():
    conn = connect_db()
    cursor = conn.cursor()
    
    # Load issues from scan
    with open('space_issues.json', 'r') as f:
        issues = json.load(f)
    
    # Focus on key databases for nys-voter-pipeline
    KEY_DATABASES = ['nys_voter_tagging', 'politik1_fec', 'politik1_nydata', 'boe_donors']
    
    print("="*80)
    print("GENERATING COMPLETE RENAME SQL")
    print("="*80)
    
    sql_lines = [
        "-- ============================================================================",
        "-- RENAME TABLES AND COLUMNS WITH SPACES",
        "-- Generated by: complete_rename_solution.py",
        "-- ============================================================================",
        "",
        "-- IMPORTANT: Review this script before executing!",
        "-- Consider backing up your databases first.",
        "",
    ]
    
    # Group by database
    by_database = {}
    for issue in issues:
        db = issue['database']
        if db not in by_database:
            by_database[db] = {'tables': [], 'columns': []}
        
        if issue['type'] == 'table':
            by_database[db]['tables'].append(issue)
        else:
            by_database[db]['columns'].append(issue)
    
    # Generate SQL for each database
    for db in sorted(by_database.keys()):
        # Only focus on key databases
        is_key_db = db in KEY_DATABASES
        
        data = by_database[db]
        total_issues = len(data['tables']) + len(data['columns'])
        
        sql_lines.append(f"\n-- {'='*76}")
        sql_lines.append(f"-- DATABASE: {db} ({total_issues} issues)")
        if is_key_db:
            sql_lines.append(f"-- STATUS: KEY DATABASE - Used by nys-voter-pipeline")
        else:
            sql_lines.append(f"-- STATUS: Secondary database - May not be actively used")
        sql_lines.append(f"-- {'='*76}")
        sql_lines.append(f"USE `{db}`;")
        sql_lines.append("")
        
        # Rename tables
        if data['tables']:
            sql_lines.append("-- STEP 1: RENAME TABLES")
            for t in data['tables']:
                sql_lines.append(f"RENAME TABLE `{t['table']}` TO `{t['new_name']}`;")
                print(f"  [TABLE] {db}.`{t['table']}` → `{t['new_name']}`")
            sql_lines.append("")
        
        # Rename columns
        if data['columns']:
            sql_lines.append("-- STEP 2: RENAME COLUMNS")
            
            # Group by table
            by_table = {}
            for c in data['columns']:
                table = c['table']
                if table not in by_table:
                    by_table[table] = []
                by_table[table].append(c)
            
            for table, columns in sorted(by_table.items()):
                sql_lines.append(f"\n-- Table: {table} ({len(columns)} columns)")
                
                for c in columns:
                    try:
                        col_def = get_column_definition(cursor, db, table, c['column'])
                        if col_def:
                            sql_lines.append(f"ALTER TABLE `{table}` CHANGE `{c['column']}` `{c['new_name']}` {col_def};")
                            print(f"  [COLUMN] {db}.{table}.`{c['column']}` → `{c['new_name']}`")
                        else:
                            sql_lines.append(f"-- ERROR: Could not get definition for {table}.`{c['column']}`")
                    except Exception as e:
                        sql_lines.append(f"-- ERROR: {table}.`{c['column']}`: {str(e)}")
        
        sql_lines.append("")
    
    # Save SQL
    with open('rename_complete.sql', 'w', encoding='utf-8') as f:
        f.write('\n'.join(sql_lines))
    
    print("\n" + "="*80)
    print("SQL SCRIPT GENERATED: rename_complete.sql")
    print("="*80)
    
    # Summary
    print("\nSUMMARY BY DATABASE:")
    for db in sorted(by_database.keys()):
        data = by_database[db]
        is_key = "⭐ KEY" if db in KEY_DATABASES else "  "
        print(f"  {is_key} {db:30} {len(data['tables'])} tables, {len(data['columns'])} columns")
    
    cursor.close()
    conn.close()

if __name__ == "__main__":
    main()
